apiVersion: apps/v1
kind: Deployment
metadata:
  name: satyashield-frontend-prod
  namespace: satyashield-prod
  labels:
    app: satyashield-frontend
    version: v1
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: satyashield-frontend
  template:
    metadata:
      labels:
        app: satyashield-frontend
        version: v1
        environment: production
    spec:
      serviceAccountName: satyashield-serviceaccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 2000
      containers:
      - name: frontend
        image: satyashield/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: satyashield-config
              key: NEXT_PUBLIC_API_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satyashield-backend-prod
  namespace: satyashield-prod
  labels:
    app: satyashield-backend
    version: v1
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: satyashield-backend
  template:
    metadata:
      labels:
        app: satyashield-backend
        version: v1
        environment: production
    spec:
      serviceAccountName: satyashield-serviceaccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 2000
      containers:
      - name: backend
        image: satyashield/backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8080
          name: websocket
        envFrom:
        - configMapRef:
            name: satyashield-config
        - secretRef:
            name: satyashield-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: satyashield-uploads-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: satyashield-logs-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satyashield-ai-engine-prod
  namespace: satyashield-prod
  labels:
    app: satyashield-ai-engine
    version: v1
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: satyashield-ai-engine
  template:
    metadata:
      labels:
        app: satyashield-ai-engine
        version: v1
        environment: production
    spec:
      serviceAccountName: satyashield-serviceaccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 2000
      containers:
      - name: ai-engine
        image: satyashield/ai-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: satyashield-ai-config
        - secretRef:
            name: satyashield-ai-secrets
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: temp-storage
          mountPath: /tmp/ai-processing
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: satyashield-models-pvc
      - name: temp-storage
        emptyDir:
          sizeLimit: 10Gi
      nodeSelector:
        accelerator: nvidia-tesla-gpu
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
